### ISSUE TITLE
Communication Problem?

### ISSUE THREAD

**Issue by zeneofa** [LibourelLab/BiofloSoftware#1]
Hi,

Thank you very much for taking the time to write this software. We currently have the BioFlo115 Fermenter running. We would like to use the BiofloSoftware to monitor and perform some basic process flow control. 

I am unfortunately a novice when it comes to port communication and protocols. When I plug in a laptop to the SCADA port using a RS-232 cable, then run the BioFloSoftware Manager. I leave the root folder as default, set the comm port COMM1 and address to 08, but all I see is a flat line at 0. I am a bit lost as to where to even start to solve this problem, any hints or tips or suggestion how to get started?

Kind Regards,
Piet

**Comment by LibourelLab** [comment]
You need to solder your own cable, following the connections described in the first figure of the additional materials of the plosone paper
